/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/layout/components/Aside/index.vue')['default']
    Breadcrumb: typeof import('./src/layout/components/Header/components/breadcrumb.vue')['default']
    ColorPicker: typeof import('./src/layout/components/ColorPicker/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Fold: typeof import('./src/layout/components/Header/components/fold.vue')['default']
    Footer: typeof import('./src/layout/components/Footer/index.vue')['default']
    FullScreen: typeof import('./src/layout/components/Header/components/FullScreen.vue')['default']
    Gradient: typeof import('./src/components/Gradient/index.vue')['default']
    Header: typeof import('./src/layout/components/Header/index.vue')['default']
    HomeCard: typeof import('./src/views/ScreenDate/components/homeCard.vue')['default']
    Input: typeof import('./src/views/LoginPage/Account/components/Input.vue')['default']
    Logo: typeof import('./src/layout/components/Logo/index.vue')['default']
    Main: typeof import('./src/layout/components/Main/index.vue')['default']
    ProfilePicture: typeof import('./src/layout/components/Header/components/profilePicture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/layout/components/Header/components/search.vue')['default']
    Setup: typeof import('./src/layout/components/Header/components/setup.vue')['default']
    Switch: typeof import('./src/components/Switch/index.vue')['default']
    Tabs_: typeof import('./src/layout/components/Tabs_/index.vue')['default']
    ThemeDrawer: typeof import('./src/layout/components/ThemeDrawer/index.vue')['default']
    UseProTable: typeof import('./src/components/useProTable/index.vue')['default']
  }
}
