/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/layout/header/components/breadcrumb.vue')['default']
    ColorPicker: typeof import('./src/layout/aside/components/colorPicker.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Fold: typeof import('./src/layout/header/components/fold.vue')['default']
    FullScreen: typeof import('./src/layout/header/components/FullScreen.vue')['default']
    Gradient: typeof import('./src/components/Gradient/index.vue')['default']
    HomeCard: typeof import('./src/views/ScreenDate/components/homeCard.vue')['default']
    Logo: typeof import('./src/layout/aside/components/logo.vue')['default']
    ProfilePicture: typeof import('./src/layout/header/components/profilePicture.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setup: typeof import('./src/layout/header/components/setup.vue')['default']
    UseProTable: typeof import('./src/components/useProTable/index.vue')['default']
  }
}
